import * as Stars_1 from './stars.js';
export { Stars_1 as Stars };
import * as CanvasHandler_1 from './canvas.js';
export { CanvasHandler_1 as CanvasHandler };
import * as AstronomyMath_1 from './math.js';
export { AstronomyMath_1 as AstronomyMath };
import * as InputHelpers_1 from './input_manipulation.js';
export { InputHelpers_1 as InputHelpers };
import * as Utility_1 from './utility.js';
export { Utility_1 as Utility };
import * as Noise_1 from './noise.js';
export { Noise_1 as Noise };
import { math_json } from '../data/math_constants.js';
export const math_constants = JSON.parse(math_json);
import { star_json } from '../data/star_templates.js';
export const template_constants = JSON.parse(star_json);
